[package]
name = "nes_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
cargo-llvm-cov = "0.6.10"
lazy_static = "1.4.0"
macroquad = "0.4.11"
serde_json = "1.0.117"
